apiVersion: v1
kind: ConfigMap
metadata:
  name: my-db-config
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password
type: Opaque
data:
  db-password: bXlwYXNzd29yZA==